(* Generated by suspend (Tue, 29 Mar 2016 14:51:30 GMT). *)

let ocaml_version_check () = false

let target () = `Xen

let unix () = false

let warn_error () = false

let xen () = false

let runtime_keys = []

